twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme:
        - 'bootstrap_4_horizontal_layout.html.twig'
        #- 'theme.html.twig'

when@test:
    twig:
        strict_variables: true
